document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln(" ");
document.writeln("<head>");
document.writeln("    <meta charset=\"utf-8\">");
document.writeln("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/hello/css/head.css\">");
document.writeln("</head>");
document.writeln(" ");
document.writeln("<body>");
document.writeln("	<div class=\"out_head\">   ");
document.writeln("		<div class='miaov_head'>");
document.writeln("    		<ul>");
document.writeln("    			  <li><a href=\"http://fightinggg.github.io/ACM/data_struct/\">数据结构</a></li>");
document.writeln("        		<li><a href=\"http://fightinggg.github.io/ACM/math/\">数论</a></li>");
document.writeln("        		<li><a href=\"http://fightinggg.github.io/ACM/graph_theory/\">图论</a></li>");
document.writeln("         	  <li><a href=\"http://fightinggg.github.io/ACM/dp/\">dp</a></li>");
document.writeln("        		<li><a href=\"http://fightinggg.github.io/ACM/string/\">字符串</a></li>");
document.writeln("        		<li><a href=\"http://fightinggg.github.io/ACM/\">黑科技</a></li>");
document.writeln("        		<li><a href=\"http://fightinggg.github.io/ACM/\">思维</a></li>");
document.writeln("        		<li><a href=\"http://fightinggg.github.io/ACM/\">计算几何</a></li>");
document.writeln("    		</ul>");
document.writeln("   		</div>");
document.writeln("   </div>");
document.writeln("</body>");
document.writeln(" ");
document.writeln("</html>");
