document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln(" ");
document.writeln("<head>");
document.writeln("    <meta charset=\"utf-8\">");
document.writeln("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/hello/css/head.css\">");
document.writeln("</head>");
document.writeln(" ");
document.writeln("<body>");
document.writeln("	<div class=\"out_head\">   ");
document.writeln("		<div class='miaov_head'>");
document.writeln("    		<ul>");
document.writeln("    			<li><a href=\"http://www.cnblogs.com/jtjds/\">数据结构</a></li>");
document.writeln("        		<li><a href=\"http://www.cnblogs.com/jtjds/\">数论</a></li>");
document.writeln("        		<li><a href=\"http://www.cnblogs.com/jtjds/\">图论</a></li>");
document.writeln("         	    <li><a href=\"http://www.cnblogs.com/jtjds/\">dp</a></li>");
document.writeln("        		<li><a href=\"http://www.cnblogs.com/jtjds/\">字符串</a></li>");
document.writeln("        		<li><a href=\"http://www.cnblogs.com/jtjds/\">黑科技</a></li>");
document.writeln("        		<li><a href=\"http://www.cnblogs.com/jtjds/\">思维</a></li>");
document.writeln("        		<li><a href=\"http://www.cnblogs.com/jtjds/\">计算几何</a></li>");
document.writeln("    		</ul>");
document.writeln("   		</div>");
document.writeln("   </div>");
document.writeln("</body>");
document.writeln(" ");
document.writeln("</html>");
