 document.writeln("   <div id=\"up\">  <center><a href=\"http://fightinggg.github.io/ACM/\">逐    梦</a></center></div>");
document.writeln("  		     	<div id=\"right\">");
 document.writeln("    					<h3><center>ACM</center></h3>");
 document.writeln("    					    						<a href=\"http://fightinggg.github.io/ACM/math/\">数论</a></br>");
 document.writeln("    					    						<a href=\"http://fightinggg.github.io/ACM/data_struct/\">数据结构</a></br>");
  document.writeln("    					   						<a href=\"http://fightinggg.github.io/ACM/string\">字符串</a></br>");
 document.writeln("    											<a href=\"http://fightinggg.github.io/ACM/dp\">dp</a></br>");
 document.writeln("    											<a href=\"http://fightinggg.github.io/ACM/graph_theory/\">图论</a></br>");
 document.writeln("    											<a href=\"http://fightinggg.github.io/ACM/computational_geometry\">计算几何</a></br>");
 document.writeln("    											<a href=\"http://fightinggg.github.io/ACM/thinging\">思维与算法</a></br>");
document.writeln("    										<a href=\"http://fightinggg.github.io/ACM/Yuki_technique/\">黑科技</a></br>");
document.writeln("    										<a href=\"http://fightinggg.github.io/ACM/acm_head_file.html\">快读</a></br>");
 document.writeln("    					</div>");
